server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.ocr-eureka.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
      
zuul:
  routes:
    races: /ms-races/**
    participants: /ms-participants/**
    
turbine:
  appConfig: web,races
  cluster-name-expression: "'default'"
